### ISSUE TITLE
Change arguments as `service` and `repo_name`

### ISSUE THREAD

**Issue by vchrombie** [Groninger-Bugbusters/grimoirelab-perceval-coveralls#2]
I was going through the source code (I know there is work pending) and coveralls documentation. It seems that coveralls supports three services (github/gitlab/bitbucket). So, does it make sense to split the `repo` into two arguments `service` and `repo_name` (or `repo`)?

This would be just a small attempt to simplify using perceval. The command after this would be
```
$ perceval coveralls github chaoss/grimoirelab-perceval
$ perceval coveralls gitlab org/repo
```

WDYT?

**Comment by DavidVisscher** [comment]
I've tried it out and it also makes more sense to me. I like this change.

:heavy_check_mark:  It's implemented in: https://github.com/Groninger-Bugbusters/grimoirelab-perceval-coveralls/commit/9ff4e733e4b915f40fa3b54661922a6dd942dae0

Is this how you had envisioned it?

**Comment by vchrombie** [comment]
Yes, the implementation looks good. I think it is much simpler now.

We can still avoid the `from calendar import timegm`, but I will open another issue for it,

Thanks for your work!
