### ISSUE TITLE
Duplicate of `retrieved_on` exists already

### ISSUE THREAD

**Issue by vchrombie** [Groninger-Bugbusters/grimoirelab-perceval-coveralls#4]
Once you have successfully integrated the coveralls plugin with perceval, you can see some items are generated by perceval. One such is the `timestamp`. This typically means when was the data (here, build info item) fetched.
```
    },
    "tag": "https://coveralls.io/github/chaoss/grimoirelab-perceval",
    "timestamp": 1642934579.751084,
    "updated_on": 1568076835.0,
    "uuid": "a836795bdaf7a49c49f05424e4875651d059432c"
}
```

I think this is exactly what the `retrieved_on` is about in your implementation.
https://github.com/Groninger-Bugbusters/grimoirelab-perceval-coveralls/blob/ce191ed0468e030899fb1e4b991d49a4e34e3c2b/perceval/backends/coverage/coveralls.py#L73-L75

In that case, I think `retrieved_on` is just a duplicate of the `timestamp` item, so we can probably remove it to avoid two similar items.

Please let me know what do you think.

**Comment by DavidVisscher** [comment]
Thanks for the info :+1: . I didn't know perceval also did this- very useful-, that indeed makes this a duplicate.

I've removed the lines that add this field in: https://github.com/Groninger-Bugbusters/grimoirelab-perceval-coveralls/commit/b15ba725f04081183bc65b06953f9f6d665b87cf

**Comment by vchrombie** [comment]
Perfect! Thanks.
